{% set name = "passhash" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/passhash-{{ version }}.tar.gz
  sha256: 915d0aad0f0512db92a2fefe7151831fc6e0ecec27b593481a4a5b5f5e283ecb

build:
  entry_points:
    - passhash = passhash:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - pyyaml ==6.0.1
    - rich ==13.5.2
    - passlib ==1.7.4
    - bcrypt ==4.0.1

test:
  imports:
    - passhash
  commands:
    - pip check
    - passhash --help
  requires:
    - pip

about:
  home: https://github.com/ReK42/passhash
  summary: Generate password hashes based on various standards.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
